KEYS = -std=c++11
all:
	g++ $(KEYS) retrangle.hpp rhombus.hpp trapezium.hpp TNtree.hpp TNtreeItem.hpp TIterator.hpp TAllocator.hpp retrangle.cpp rhombus.cpp trapezium.cpp TNtree.cpp TNtreeItem.cpp TAllocators.cpp main.cpp -o 6lab 