KEYS = -pedantic -Wall -Werror -Wno-sign-compare -lm -g
all:
	g++ main.cpp figure.hpp retrangle.hpp retrangle.cpp rhombus.hpp rhombus.cpp trapezium.hpp trapezium.cpp TNtree.cpp TNtree.hpp TNtreeItem.hpp TNtreeItem.cpp -o 1lab $(KEYS)