KEYS = -std=c++11
all:
	g++ $(KEYS) figure.h retrangle.h rhombus.h trapezium.h TNtree.h TIterator.h TAllocator.h TMassive.h figure.cpp retrangle.cpp rhombus.cpp trapezium.cpp TAllocators.cpp main.cpp -o 7lab 